bash scripts/script_simulate_data.sh
bash scripts/script_linreg.sh
bash scripts/script_sumhers.sh
bash scripts/script_cors.sh
bash scripts/script_classical_prs.sh
bash scripts/script_bolt_predict.sh
bash scripts/script_megaprs.sh
Rscript r-analysis/megaprs.R
Rscript r-analysis/manhattan.R
Rscript r-analysis/classical_prs.R