import os

MODELS = ["lasso", "ridge", "bolt", "bayesr"]

def get_mem_mb(wildcards, attempt):
    return attempt * 16000

rule all:
    input: 
        "data/sumstats/snps.list",
        "data/bed/chr6.bed",
        "results/snphers/sumher.ind.hers",
        expand("results/megaprs/{model}/{model}.effects", model=MODELS),
        expand("results/megaprs/{model}/score.cors", model=MODELS)
        
include: "rules/baseqc.smk"
include: "rules/targetqc.smk"
include: "rules/sumtag.smk"
include: "rules/megaprs.smk"
